notifications:
  email:
    recipients:
      - drachels@drachels.com
    on_success: always
on_failure: always

language: php

os: linux

sudo: true

dist: xenial

addons:
  firefox: "47.0.1"
  postgresql: "9.6"
  apt:
    packages:
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  include:
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_33_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_33_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_34_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_34_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_35_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_35_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_36_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_36_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_37_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_37_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_38_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_38_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.2
      env: 
        DB=pgsql
        MOODLE_BRANCH=master
        MOODLE_CI_VERSION=2
    - php: 7.2
      env: 
        DB=mysqli
        MOODLE_BRANCH=master
        MOODLE_CI_VERSION=2

before_install:
  - phpenv config-rm xdebug.ini
  #- nvm install 8.9
  #- nvm use 8.9
  - nvm install 14.0.0
  - nvm use 14.0.0
  - cd ../..
  - if [[ $MOODLE_CI_VERSION == 1 ]];
    then composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^1;
    else composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2;
    fi
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
    - >
        if [ "$DB" = 'mysqli' ];
        then
            sudo mkdir /mnt/ramdisk
            sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
            sudo service mysql stop
            sudo mv /var/lib/mysql /mnt/ramdisk
            sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
            sudo service mysql restart
        fi
    - >
        if [ "$DB" = 'pgsql' ];
        then
            sudo mkdir /mnt/ramdisk
            sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
            sudo service postgresql stop
            sudo mv /var/lib/postgresql /mnt/ramdisk
            sudo ln -s /mnt/ramdisk/postgresql /var/lib/postgresql
            sudo service postgresql start 9.6
        fi
    - >
        if [ "$TASK" = 'GRUNT' ];
        then
            nvm install $NVM_VERSION ;
            nvm use $NVM_VERSION ;
        fi

  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - if [[ $MOODLE_CI_VERSION == 2 ]];
    then
      moodle-plugin-ci savepoints;
      moodle-plugin-ci mustache;
      moodle-plugin-ci grunt;
    fi
  - moodle-plugin-ci phpunit
  #- moodle-plugin-ci behat
